# Generated by Django 5.0.2 on 2024-02-23 20:27

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Service Provider')], default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(null=True, upload_to=myapp.models.image_file_path)),
            ],
        ),
    ]
